version: '1'
services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_HOST}:${BACKEND_HOST}
    environment:
      EXCHANGE_RATE_ACCESS_KEY: ${EXCHANGE_RATE_ACCESS_KEY}
      EXCHANGE_RATE_BASE_URL: ${EXCHANGE_RATE_BASE_URL}
      BACKEND_HOST: ${BACKEND_HOST}

  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.tests
    depends_on:
      - backend

  frontend:
    build: ./frontend