import type { Metadata } from 'next'
import { CurrentThemeProvider } from '@/contexts/CurrentThemeProvider'
import { LanguageContextProvider } from '@/contexts/LanguageContextProvider'
import StyledComponentsRegistry from '@/configs/libs/StyledComponentsRegistry'

export const metadata: Metadata = {
  title: 'Currency Converter',
  description: 'Generated by create next app',
}

import '/node_modules/flag-icons/css/flag-icons.min.css';

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }]
}

interface RootProps {
  children: React.ReactNode;
  params: { lang: string };
}

export default function LangLayout({
  children,
  params
}: RootProps) {
  return (
    <html lang={params.lang}>
      <body>
        <StyledComponentsRegistry>
          <CurrentThemeProvider>
            <LanguageContextProvider>
              {children}
            </LanguageContextProvider>
          </CurrentThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
