import type { Metadata } from 'next'
import { CurrentThemeProvider } from '@/contexts/CurrentThemeProvider'
import { LanguageContextProvider } from '@/contexts/LanguageContextProvider'
import StyledComponentsRegistry from '@/configs/libs/StyledComponentsRegistry'

export const metadata: Metadata = {
  title: 'Currency Converter',
  description: 'Generated by create next app',
}

import '/node_modules/flag-icons/css/flag-icons.min.css';
import { I18nProviderClient } from '@/i18n/locales/client'

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }]
}

interface RootProps {
  children: React.ReactNode;
  params: { lang: string };
}

export default function LangLayout({
  children,
  params
}: RootProps) {
  return (
    <html lang={params.lang}>
      <body>
        <StyledComponentsRegistry>
          <I18nProviderClient locale={params.lang}>
            <CurrentThemeProvider>
              <LanguageContextProvider>
                {children}
              </LanguageContextProvider>
            </CurrentThemeProvider>
          </I18nProviderClient>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
