import { Currencies } from '../../@types';

export const EnCountries: Currencies = {
  EUR: {
    unit_value: 0,
    country_name: 'European Union',
    currency_code: 'EUR',
    currency_name: 'Euro',
    monetary_symbol: '€',
    flag_code: 'eu',
  },
  AED: {
    unit_value: 0,
    country_name: 'United Arab Emirates Dirham',
    currency_code: 'AED',
    currency_name: 'Dirham',
    monetary_symbol: 'د.إ',
    flag_code: 'ae',
  },
  AFN: {
    unit_value: 0,
    country_name: 'Afghan Afghani',
    currency_code: 'AFN',
    currency_name: 'Afghani',
    monetary_symbol: '؋',
    flag_code: 'af',
  },
  ALL: {
    unit_value: 0,
    country_name: 'Albanian Lek',
    currency_code: 'ALL',
    currency_name: 'Lek',
    monetary_symbol: 'L',
    flag_code: 'al',
  },
  AMD: {
    unit_value: 0,
    country_name: 'Armenian Dram',
    currency_code: 'AMD',
    currency_name: 'Dram',
    monetary_symbol: '֏',
    flag_code: 'am',
  },
  ANG: {
    unit_value: 0,
    country_name: 'Netherlands Antillean Guilder',
    currency_code: 'ANG',
    currency_name: 'Guilder',
    monetary_symbol: 'ƒ',
    flag_code: 'nl',
  },
  AOA: {
    unit_value: 0,
    country_name: 'Angolan Kwanza',
    currency_code: 'AOA',
    currency_name: 'Kwanza',
    monetary_symbol: 'Kz',
    flag_code: 'ao',
  },
  ARS: {
    unit_value: 0,
    country_name: 'Argentine Peso',
    currency_code: 'ARS',
    currency_name: 'Peso',
    monetary_symbol: '$',
    flag_code: 'ar',
  },
  AUD: {
    unit_value: 0,
    country_name: 'Australian Dollar',
    currency_code: 'AUD',
    currency_name: 'Dollar',
    monetary_symbol: '$',
    flag_code: 'au',
  },
  AWG: {
    unit_value: 0,
    country_name: 'Aruba',
    currency_code: 'AWG',
    currency_name: 'Aruban Florin',
    monetary_symbol: 'Afl',
    flag_code: 'aw',
  },
  AZN: {
    unit_value: 0,
    country_name: 'Azerbaijan',
    currency_code: 'AZN',
    currency_name: 'Azerbaijani Manat',
    monetary_symbol: '₼',
    flag_code: 'az',
  },
  BAM: {
    unit_value: 0,
    country_name: 'Bosnia and Herzegovina',
    currency_code: 'BAM',
    currency_name: 'Bosnia-Herzegovina Convertible Mark',
    monetary_symbol: 'KM',
    flag_code: 'ba',
  },
  BBD: {
    unit_value: 0,
    country_name: 'Barbados',
    currency_code: 'BBD',
    currency_name: 'Barbadian Dollar',
    monetary_symbol: 'Bds$',
    flag_code: 'bb',
  },
  BDT: {
    unit_value: 0,
    country_name: 'Bangladesh',
    currency_code: 'BDT',
    currency_name: 'Bangladeshi Taka',
    monetary_symbol: '৳',
    flag_code: 'bd',
  },
  BGN: {
    unit_value: 0,
    country_name: 'Bulgaria',
    currency_code: 'BGN',
    currency_name: 'Bulgarian Lev',
    monetary_symbol: 'лв',
    flag_code: 'bg',
  },
  BHD: {
    unit_value: 0,
    country_name: 'Bahrain',
    currency_code: 'BHD',
    currency_name: 'Bahraini Dinar',
    monetary_symbol: 'BD',
    flag_code: 'bh',
  },
  BIF: {
    unit_value: 0,
    country_name: 'Burundi',
    currency_code: 'BIF',
    currency_name: 'Burundian Franc',
    monetary_symbol: 'FBu',
    flag_code: 'bi',
  },
  BMD: {
    unit_value: 0,
    country_name: 'Bermuda',
    currency_code: 'BMD',
    currency_name: 'Bermudian Dollar',
    monetary_symbol: 'BD$',
    flag_code: 'bm',
  },
  BND: {
    unit_value: 0,
    country_name: 'Brunei',
    currency_code: 'BND',
    currency_name: 'Brunei Dollar',
    monetary_symbol: 'B$',
    flag_code: 'bn',
  },
  BOB: {
    unit_value: 0,
    country_name: 'Bolivia',
    currency_code: 'BOB',
    currency_name: 'Bolivian Boliviano',
    monetary_symbol: 'Bs.',
    flag_code: 'bo',
  },
  BRL: {
    unit_value: 0,
    country_name: 'Brazil',
    currency_code: 'BRL',
    currency_name: 'Brazilian Real',
    monetary_symbol: 'R$',
    flag_code: 'br',
  },
  BSD: {
    unit_value: 0,
    country_name: 'Bahamas',
    currency_code: 'BSD',
    currency_name: 'Bahamian Dollar',
    monetary_symbol: 'BSD$',
    flag_code: 'bs',
  },
  BTN: {
    unit_value: 0,
    country_name: 'Bhutan',
    currency_code: 'BTN',
    currency_name: 'Bhutanese Ngultrum',
    monetary_symbol: 'Nu.',
    flag_code: 'bh',
  },
  BWP: {
    unit_value: 0,
    country_name: 'Botswana',
    currency_code: 'BWP',
    currency_name: 'Botswana Pula',
    monetary_symbol: 'P',
    flag_code: 'bw',
  },
  BYN: {
    unit_value: 0,
    country_name: 'Belarus',
    currency_code: 'BYN',
    currency_name: 'Belarusian Ruble',
    monetary_symbol: 'Br',
    flag_code: 'by',
  },
  BZD: {
    unit_value: 0,
    country_name: 'Belize',
    currency_code: 'BZD',
    currency_name: 'Belize Dollar',
    monetary_symbol: 'BZ$',
    flag_code: 'bz',
  },
  CAD: {
    unit_value: 0,
    country_name: 'Canada',
    currency_code: 'CAD',
    currency_name: 'Canadian Dollar',
    monetary_symbol: 'CA$',
    flag_code: 'ca',
  },
  CDF: {
    unit_value: 0,
    country_name: 'Democratic Republic of the Congo',
    currency_code: 'CDF',
    currency_name: 'Congolese Franc',
    monetary_symbol: 'FC',
    flag_code: 'cd',
  },
  CHF: {
    unit_value: 0,
    country_name: 'Switzerland',
    currency_code: 'CHF',
    currency_name: 'Swiss Franc',
    monetary_symbol: 'CHF',
    flag_code: 'ch',
  },
  CLP: {
    unit_value: 0,
    country_name: 'Chile',
    currency_code: 'CLP',
    currency_name: 'Chilean Peso',
    monetary_symbol: 'CLP$',
    flag_code: 'cl',
  },
  CNY: {
    unit_value: 0,
    country_name: 'China',
    currency_code: 'CNY',
    currency_name: 'Chinese Renminbi',
    monetary_symbol: '¥',
    flag_code: 'cn',
  },
  COP: {
    unit_value: 0,
    country_name: 'Colombia',
    currency_code: 'COP',
    currency_name: 'Colombian Peso',
    monetary_symbol: 'COL$',
    flag_code: 'co',
  },
  CRC: {
    unit_value: 0,
    country_name: 'Costa Rica',
    currency_code: 'CRC',
    currency_name: 'Costa Rican Colón',
    monetary_symbol: '₡',
    flag_code: 'cr',
  },
  CUP: {
    unit_value: 0,
    country_name: 'Cuba',
    currency_code: 'CUP',
    currency_name: 'Cuban Peso',
    monetary_symbol: 'CUP$',
    flag_code: 'cu',
  },
  CVE: {
    unit_value: 0,
    country_name: 'Cabo Verde',
    currency_code: 'CVE',
    currency_name: 'Cape Verdean Escudo',
    monetary_symbol: 'Esc',
    flag_code: 'cv',
  },
  CZK: {
    unit_value: 0,
    country_name: 'Czech Republic',
    currency_code: 'CZK',
    currency_name: 'Czech Koruna',
    monetary_symbol: 'Kč',
    flag_code: 'cz',
  },
  DJF: {
    unit_value: 0,
    country_name: 'Djibouti',
    currency_code: 'DJF',
    currency_name: 'Djiboutian Franc',
    monetary_symbol: 'Fdj',
    flag_code: 'dj',
  },
  DKK: {
    unit_value: 0,
    country_name: 'Denmark',
    currency_code: 'DKK',
    currency_name: 'Danish Krone',
    monetary_symbol: 'kr',
    flag_code: 'dk',
  },
  DOP: {
    unit_value: 0,
    country_name: 'Dominican Republic',
    currency_code: 'DOP',
    currency_name: 'Dominican Peso',
    monetary_symbol: 'RD$',
    flag_code: 'do',
  },
  DZD: {
    unit_value: 0,
    country_name: 'Algeria',
    currency_code: 'DZD',
    currency_name: 'Algerian Dinar',
    monetary_symbol: 'د.ج',
    flag_code: 'dz',
  },
  EGP: {
    unit_value: 0,
    country_name: 'Egypt',
    currency_code: 'EGP',
    currency_name: 'Egyptian Pound',
    monetary_symbol: 'ج.م',
    flag_code: 'eg',
  },
  ERN: {
    unit_value: 0,
    country_name: 'Eritrea',
    currency_code: 'ERN',
    currency_name: 'Eritrean Nakfa',
    monetary_symbol: 'Nfk',
    flag_code: 'er',
  },
  ETB: {
    unit_value: 0,
    country_name: 'Ethiopia',
    currency_code: 'ETB',
    currency_name: 'Ethiopian Birr',
    monetary_symbol: 'Br',
    flag_code: 'et',
  },
  FJD: {
    unit_value: 0,
    country_name: 'Fiji',
    currency_code: 'FJD',
    currency_name: 'Fijian Dollar',
    monetary_symbol: 'FJ$',
    flag_code: 'fj',
  },
  FKP: {
    unit_value: 0,
    country_name: 'Falkland Islands (Malvinas)',
    currency_code: 'FKP',
    currency_name: 'Falkland Islands Pound',
    monetary_symbol: 'FK£',
    flag_code: 'fk',
  },
  FOK: {
    unit_value: 0,
    country_name: 'Faroe Islands',
    currency_code: 'FOK',
    currency_name: 'Faroese Króna',
    monetary_symbol: 'kr',
    flag_code: 'fo',
  },
  GBP: {
    unit_value: 0,
    country_name: 'United Kingdom',
    currency_code: 'GBP',
    currency_name: 'British Pound Sterling',
    monetary_symbol: '£',
    flag_code: 'gb',
  },
  GEL: {
    unit_value: 0,
    country_name: 'Georgia',
    currency_code: 'GEL',
    currency_name: 'Georgian Lari',
    monetary_symbol: '₾',
    flag_code: 'ge',
  },
  GGP: {
    unit_value: 0,
    country_name: 'Guernsey',
    currency_code: 'GGP',
    currency_name: 'Guernsey Pound',
    monetary_symbol: '£',
    flag_code: 'gg',
  },
  GHS: {
    unit_value: 0,
    country_name: 'Ghana',
    currency_code: 'GHS',
    currency_name: 'Ghanaian Cedi',
    monetary_symbol: 'GH₵',
    flag_code: 'gh',
  },
  GIP: {
    unit_value: 0,
    country_name: 'Gibraltar',
    currency_code: 'GIP',
    currency_name: 'Gibraltar Pound',
    monetary_symbol: '£',
    flag_code: 'gi',
  },
  GMD: {
    unit_value: 0,
    country_name: 'Gambia',
    currency_code: 'GMD',
    currency_name: 'Gambian Dalasi',
    monetary_symbol: 'D',
    flag_code: 'gm',
  },
  GNF: {
    unit_value: 0,
    country_name: 'Guinea',
    currency_code: 'GNF',
    currency_name: 'Guinean Franc',
    monetary_symbol: 'FG',
    flag_code: 'gn',
  },
  GTQ: {
    unit_value: 0,
    country_name: 'Guatemala',
    currency_code: 'GTQ',
    currency_name: 'Guatemalan Quetzal',
    monetary_symbol: 'Q',
    flag_code: 'gt',
  },
  GYD: {
    unit_value: 0,
    country_name: 'Guyana',
    currency_code: 'GYD',
    currency_name: 'Guyanese Dollar',
    monetary_symbol: 'GY$',
    flag_code: 'gy',
  },
  HKD: {
    unit_value: 0,
    country_name: 'Hong Kong',
    currency_code: 'HKD',
    currency_name: 'Hong Kong Dollar',
    monetary_symbol: 'HK$',
    flag_code: 'hk',
  },
  HNL: {
    unit_value: 0,
    country_name: 'Honduras',
    currency_code: 'HNL',
    currency_name: 'Honduran Lempira',
    monetary_symbol: 'L',
    flag_code: 'hn',
  },
  HRK: {
    unit_value: 0,
    country_name: 'Croatia',
    currency_code: 'HRK',
    currency_name: 'Croatian Kuna',
    monetary_symbol: 'kn',
    flag_code: 'hr',
  },
  HTG: {
    unit_value: 0,
    country_name: 'Haiti',
    currency_code: 'HTG',
    currency_name: 'Haitian Gourde',
    monetary_symbol: 'G',
    flag_code: 'ht',
  },
  HUF: {
    unit_value: 0,
    country_name: 'Hungary',
    currency_code: 'HUF',
    currency_name: 'Hungarian Forint',
    monetary_symbol: 'Ft',
    flag_code: 'hu',
  },
  IDR: {
    unit_value: 0,
    country_name: 'Indonesia',
    currency_code: 'IDR',
    currency_name: 'Indonesian Rupiah',
    monetary_symbol: 'Rp',
    flag_code: 'id',
  },
  ILS: {
    unit_value: 0,
    country_name: 'Israel',
    currency_code: 'ILS',
    currency_name: 'Israeli New Shekel',
    monetary_symbol: '₪',
    flag_code: 'is',
  },
  IMP: {
    unit_value: 0,
    country_name: 'Isle of Man',
    currency_code: 'IMP',
    currency_name: 'Isle of Man Pound',
    monetary_symbol: '£',
    flag_code: 'im',
  },
  INR: {
    unit_value: 0,
    country_name: 'India',
    currency_code: 'INR',
    currency_name: 'Indian Rupee',
    monetary_symbol: '₹',
    flag_code: 'in',
  },
  IQD: {
    unit_value: 0,
    country_name: 'Iraq',
    currency_code: 'IQD',
    currency_name: 'Iraqi Dinar',
    monetary_symbol: 'ع.د',
    flag_code: 'iq',
  },
  IRR: {
    unit_value: 0,
    country_name: 'Iran',
    currency_code: 'IRR',
    currency_name: 'Iranian Rial',
    monetary_symbol: '﷼',
    flag_code: 'ir',
  },
  ISK: {
    unit_value: 0,
    country_name: 'Iceland',
    currency_code: 'ISK',
    currency_name: 'Icelandic Króna',
    monetary_symbol: 'kr',
    flag_code: 'is',
  },
  JEP: {
    unit_value: 0,
    country_name: 'Jersey',
    currency_code: 'JEP',
    currency_name: 'Jersey Pound',
    monetary_symbol: '£',
    flag_code: 'je',
  },
  JMD: {
    unit_value: 0,
    country_name: 'Jamaica',
    currency_code: 'JMD',
    currency_name: 'Jamaican Dollar',
    monetary_symbol: 'J$',
    flag_code: 'jm',
  },
  JOD: {
    unit_value: 0,
    country_name: 'Jordan',
    currency_code: 'JOD',
    currency_name: 'Jordanian Dinar',
    monetary_symbol: 'د.ا',
    flag_code: 'jo',
  },
  JPY: {
    unit_value: 0,
    country_name: 'Japan',
    currency_code: 'JPY',
    currency_name: 'Japanese Yen',
    monetary_symbol: '¥',
    flag_code: 'jp',
  },
  KES: {
    unit_value: 0,
    country_name: 'Kenya',
    currency_code: 'KES',
    currency_name: 'Kenyan Shilling',
    monetary_symbol: 'Ksh',
    flag_code: 'ke',
  },
  KGS: {
    unit_value: 0,
    country_name: 'Kyrgyzstan',
    currency_code: 'KGS',
    currency_name: 'Kyrgystani Som',
    monetary_symbol: 'с',
    flag_code: 'kg',
  },
  KHR: {
    unit_value: 0,
    country_name: 'Cambodia',
    currency_code: 'KHR',
    currency_name: 'Cambodian Riel',
    monetary_symbol: '៛',
    flag_code: 'kh',
  },
  KID: {
    unit_value: 0,
    country_name: 'Kiribati',
    currency_code: 'KID',
    currency_name: 'Kiribati Dollar',
    monetary_symbol: '$',
    flag_code: 'ki',
  },
  KMF: {
    unit_value: 0,
    country_name: 'Comoros',
    currency_code: 'KMF',
    currency_name: 'Comorian Franc',
    monetary_symbol: 'CF',
    flag_code: 'km',
  },
  KRW: {
    unit_value: 0,
    country_name: 'South Korea',
    currency_code: 'KRW',
    currency_name: 'South Korean Won',
    monetary_symbol: '₩',
    flag_code: 'kr',
  },
  KWD: {
    unit_value: 0,
    country_name: 'Kuwait',
    currency_code: 'KWD',
    currency_name: 'Kuwaiti Dinar',
    monetary_symbol: 'د.ك',
    flag_code: 'kw',
  },
  KYD: {
    unit_value: 0,
    country_name: 'Cayman Islands',
    currency_code: 'KYD',
    currency_name: 'Cayman Islands Dollar',
    monetary_symbol: '$',
    flag_code: 'ky',
  },
  KZT: {
    unit_value: 0,
    country_name: 'Kazakhstan',
    currency_code: 'KZT',
    currency_name: 'Kazakhstani Tenge',
    monetary_symbol: '₸',
    flag_code: 'kz',
  },
  LAK: {
    unit_value: 0,
    country_name: 'Laos',
    currency_code: 'LAK',
    currency_name: 'Laotian Kip',
    monetary_symbol: '₭',
    flag_code: 'la',
  },
  LBP: {
    unit_value: 0,
    country_name: 'Lebanon',
    currency_code: 'LBP',
    currency_name: 'Lebanese Pound',
    monetary_symbol: 'ل.ل',
    flag_code: 'lb',
  },
  LKR: {
    unit_value: 0,
    country_name: 'Sri Lanka',
    currency_code: 'LKR',
    currency_name: 'Sri Lankan Rupee',
    monetary_symbol: 'රු',
    flag_code: 'lk',
  },
  LRD: {
    unit_value: 0,
    country_name: 'Liberia',
    currency_code: 'LRD',
    currency_name: 'Liberian Dollar',
    monetary_symbol: '$',
    flag_code: 'lr',
  },
  LSL: {
    unit_value: 0,
    country_name: 'Lesotho',
    currency_code: 'LSL',
    currency_name: 'Lesotho Loti',
    monetary_symbol: 'L',
    flag_code: 'ls',
  },
  LYD: {
    unit_value: 0,
    country_name: 'Libya',
    currency_code: 'LYD',
    currency_name: 'Libyan Dinar',
    monetary_symbol: 'ل.د',
    flag_code: 'ly',
  },
  MAD: {
    unit_value: 0,
    country_name: 'Morocco',
    currency_code: 'MAD',
    currency_name: 'Moroccan Dirham',
    monetary_symbol: 'د.م.',
    flag_code: 'ma',
  },
  MDL: {
    unit_value: 0,
    country_name: 'Moldova',
    currency_code: 'MDL',
    currency_name: 'Moldovan Leu',
    monetary_symbol: 'L',
    flag_code: 'md',
  },
  MGA: {
    unit_value: 0,
    country_name: 'Madagascar',
    currency_code: 'MGA',
    currency_name: 'Malagasy Ariary',
    monetary_symbol: 'Ar',
    flag_code: 'mg',
  },
  MKD: {
    unit_value: 0,
    country_name: 'North Macedonia',
    currency_code: 'MKD',
    currency_name: 'Macedonian Denar',
    monetary_symbol: 'ден',
    flag_code: 'mk',
  },
  MMK: {
    unit_value: 0,
    country_name: 'Myanmar',
    currency_code: 'MMK',
    currency_name: 'Myanmar Kyat',
    monetary_symbol: 'Ks',
    flag_code: 'mm',
  },
  MNT: {
    unit_value: 0,
    country_name: 'Mongolia',
    currency_code: 'MNT',
    currency_name: 'Mongolian Tugrik',
    monetary_symbol: '₮',
    flag_code: 'mn',
  },
  MOP: {
    unit_value: 0,
    country_name: 'Macau',
    currency_code: 'MOP',
    currency_name: 'Macanese Pataca',
    monetary_symbol: 'P',
    flag_code: 'mo',
  },
  MRU: {
    unit_value: 0,
    country_name: 'Mauritania',
    currency_code: 'MRU',
    currency_name: 'Mauritanian Ouguiya',
    monetary_symbol: 'UM',
    flag_code: 'mr',
  },
  MUR: {
    unit_value: 0,
    country_name: 'Mauritius',
    currency_code: 'MUR',
    currency_name: 'Mauritian Rupee',
    monetary_symbol: '₨',
    flag_code: 'mu',
  },
  MVR: {
    unit_value: 0,
    country_name: 'Maldives',
    currency_code: 'MVR',
    currency_name: 'Maldivian Rufiyaa',
    monetary_symbol: 'ރ.',
    flag_code: 'mv',
  },
  MWK: {
    unit_value: 0,
    country_name: 'Malawi',
    currency_code: 'MWK',
    currency_name: 'Malawian Kwacha',
    monetary_symbol: 'MK',
    flag_code: 'mw',
  },
  MXN: {
    unit_value: 0,
    country_name: 'Mexico',
    currency_code: 'MXN',
    currency_name: 'Mexican Peso',
    monetary_symbol: '$',
    flag_code: 'mx',
  },
  MYR: {
    unit_value: 0,
    country_name: 'Malaysia',
    currency_code: 'MYR',
    currency_name: 'Malaysian Ringgit',
    monetary_symbol: 'RM',
    flag_code: 'my',
  },
  MZN: {
    unit_value: 0,
    country_name: 'Mozambique',
    currency_code: 'MZN',
    currency_name: 'Mozambican Metical',
    monetary_symbol: 'MT',
    flag_code: 'mz',
  },
  NAD: {
    unit_value: 0,
    country_name: 'Namibia',
    currency_code: 'NAD',
    currency_name: 'Namibian Dollar',
    monetary_symbol: '$',
    flag_code: 'na',
  },
  NGN: {
    unit_value: 0,
    country_name: 'Nigeria',
    currency_code: 'NGN',
    currency_name: 'Nigerian Naira',
    monetary_symbol: '₦',
    flag_code: 'ng',
  },
  NIO: {
    unit_value: 0,
    country_name: 'Nicaragua',
    currency_code: 'NIO',
    currency_name: 'Nicaraguan Córdoba',
    monetary_symbol: 'C$',
    flag_code: 'ni',
  },
  NOK: {
    unit_value: 0,
    country_name: 'Norway',
    currency_code: 'NOK',
    currency_name: 'Norwegian Krone',
    monetary_symbol: 'kr',
    flag_code: 'no',
  },
  NPR: {
    unit_value: 0,
    country_name: 'Nepal',
    currency_code: 'NPR',
    currency_name: 'Nepalese Rupee',
    monetary_symbol: 'रू',
    flag_code: 'np',
  },
  NZD: {
    unit_value: 0,
    country_name: 'New Zealand',
    currency_code: 'NZD',
    currency_name: 'New Zealand Dollar',
    monetary_symbol: '$',
    flag_code: 'nz',
  },
  OMR: {
    unit_value: 0,
    country_name: 'Oman',
    currency_code: 'OMR',
    currency_name: 'Omani Rial',
    monetary_symbol: 'ر.ع.',
    flag_code: 'om',
  },
  PAB: {
    unit_value: 0,
    country_name: 'Panama',
    currency_code: 'PAB',
    currency_name: 'Panamanian Balboa',
    monetary_symbol: 'B/.',
    flag_code: 'pa',
  },
  PEN: {
    unit_value: 0,
    country_name: 'Peru',
    currency_code: 'PEN',
    currency_name: 'Peruvian Nuevo Sol',
    monetary_symbol: 'S/.',
    flag_code: 'pe',
  },
  PGK: {
    unit_value: 0,
    country_name: 'Papua New Guinea',
    currency_code: 'PGK',
    currency_name: 'Papua New Guinean Kina',
    monetary_symbol: 'K',
    flag_code: 'pg',
  },
  PHP: {
    unit_value: 0,
    country_name: 'Philippines',
    currency_code: 'PHP',
    currency_name: 'Philippine Peso',
    monetary_symbol: '₱',
    flag_code: 'ph',
  },
  PKR: {
    unit_value: 0,
    country_name: 'Pakistan',
    currency_code: 'PKR',
    currency_name: 'Pakistani Rupee',
    monetary_symbol: '₨',
    flag_code: 'pk',
  },
  PLN: {
    unit_value: 0,
    country_name: 'Poland',
    currency_code: 'PLN',
    currency_name: 'Polish Złoty',
    monetary_symbol: 'zł',
    flag_code: 'pl',
  },
  PYG: {
    unit_value: 0,
    country_name: 'Paraguay',
    currency_code: 'PYG',
    currency_name: 'Paraguayan Guarani',
    monetary_symbol: '₲',
    flag_code: 'py',
  },
  QAR: {
    unit_value: 0,
    country_name: 'Qatar',
    currency_code: 'QAR',
    currency_name: 'Qatari Rial',
    monetary_symbol: 'ر.ق.',
    flag_code: 'qa',
  },
  RON: {
    unit_value: 0,
    country_name: 'Romania',
    currency_code: 'RON',
    currency_name: 'Romanian Leu',
    monetary_symbol: 'lei',
    flag_code: 'ro',
  },
  RSD: {
    unit_value: 0,
    country_name: 'Serbia',
    currency_code: 'RSD',
    currency_name: 'Serbian Dinar',
    monetary_symbol: 'дин.',
    flag_code: 'rs',
  },
  RUB: {
    unit_value: 0,
    country_name: 'Russia',
    currency_code: 'RUB',
    currency_name: 'Russian Ruble',
    monetary_symbol: '₽',
    flag_code: 'ru',
  },
  RWF: {
    unit_value: 0,
    country_name: 'Rwanda',
    currency_code: 'RWF',
    currency_name: 'Rwandan Franc',
    monetary_symbol: 'FRw',
    flag_code: 'rw',
  },
  SAR: {
    unit_value: 0,
    country_name: 'Saudi Arabia',
    currency_code: 'SAR',
    currency_name: 'Saudi Riyal',
    monetary_symbol: 'ر.س.',
    flag_code: 'sa',
  },
  SBD: {
    unit_value: 0,
    country_name: 'Solomon Islands',
    currency_code: 'SBD',
    currency_name: 'Solomon Islands Dollar',
    monetary_symbol: '$',
    flag_code: 'sb',
  },
  SCR: {
    unit_value: 0,
    country_name: 'Seychelles',
    currency_code: 'SCR',
    currency_name: 'Seychellois Rupee',
    monetary_symbol: '₨',
    flag_code: 'sc',
  },
  SDG: {
    unit_value: 0,
    country_name: 'Sudan',
    currency_code: 'SDG',
    currency_name: 'Sudanese Pound',
    monetary_symbol: '£',
    flag_code: 'sd',
  },
  SEK: {
    unit_value: 0,
    country_name: 'Sweden',
    currency_code: 'SEK',
    currency_name: 'Swedish Krona',
    monetary_symbol: 'kr',
    flag_code: 'se',
  },
  SGD: {
    unit_value: 0,
    country_name: 'Singapore',
    currency_code: 'SGD',
    currency_name: 'Singapore Dollar',
    monetary_symbol: '$',
    flag_code: 'sg',
  },
  SHP: {
    unit_value: 0,
    country_name: 'Saint Helena',
    currency_code: 'SHP',
    currency_name: 'Saint Helena Pound',
    monetary_symbol: '£',
    flag_code: 'sh',
  },
  SLE: {
    unit_value: 0,
    country_name: 'Sierra Leone',
    currency_code: 'SLE',
    currency_name: 'Sierra Leonean Leone',
    monetary_symbol: 'Le',
    flag_code: 'sl',
  },
  SLL: {
    unit_value: 0,
    country_name: 'Sierra Leone',
    currency_code: 'SLL',
    currency_name: 'Sierra Leonean Leone',
    monetary_symbol: 'Le',
    flag_code: 'sl',
  },
  SOS: {
    unit_value: 0,
    country_name: 'Somalia',
    currency_code: 'SOS',
    currency_name: 'Somali Shilling',
    monetary_symbol: 'Sh',
    flag_code: 'so',
  },
  SRD: {
    unit_value: 0,
    country_name: 'Suriname',
    currency_code: 'SRD',
    currency_name: 'Surinamese Dollar',
    monetary_symbol: '$',
    flag_code: 'sr',
  },
  SSP: {
    unit_value: 0,
    country_name: 'South Sudan',
    currency_code: 'SSP',
    currency_name: 'South Sudanese Pound',
    monetary_symbol: '£',
    flag_code: 'ss',
  },
  STN: {
    unit_value: 0,
    country_name: 'São Tomé and Príncipe',
    currency_code: 'STN',
    currency_name: 'São Tomé and Príncipe Dobra',
    monetary_symbol: 'Db',
    flag_code: 'st',
  },
  SYP: {
    unit_value: 0,
    country_name: 'Syria',
    currency_code: 'SYP',
    currency_name: 'Syrian Pound',
    monetary_symbol: 'ل.س',
    flag_code: 'sy',
  },
  SZL: {
    unit_value: 0,
    country_name: 'Eswatini',
    currency_code: 'SZL',
    currency_name: 'Swazi Lilangeni',
    monetary_symbol: 'E',
    flag_code: 'sz',
  },
  THB: {
    unit_value: 0,
    country_name: 'Thailand',
    currency_code: 'THB',
    currency_name: 'Thai Baht',
    monetary_symbol: '฿',
    flag_code: 'th',
  },
  TJS: {
    unit_value: 0,
    country_name: 'Tajikistan',
    currency_code: 'TJS',
    currency_name: 'Tajikistani Somoni',
    monetary_symbol: 'ЅМ',
    flag_code: 'tj',
  },
  TMT: {
    unit_value: 0,
    country_name: 'Turkmenistan',
    currency_code: 'TMT',
    currency_name: 'Turkmenistani Manat',
    monetary_symbol: 'T',
    flag_code: 'tm',
  },
  TND: {
    unit_value: 0,
    country_name: 'Tunisia',
    currency_code: 'TND',
    currency_name: 'Tunisian Dinar',
    monetary_symbol: 'د.ت',
    flag_code: 'tn',
  },
  TOP: {
    unit_value: 0,
    country_name: 'Tonga',
    currency_code: 'TOP',
    currency_name: 'Tongan Paʻanga',
    monetary_symbol: 'T$',
    flag_code: 'to',
  },
  TRY: {
    unit_value: 0,
    country_name: 'Turkey',
    currency_code: 'TRY',
    currency_name: 'Turkish Lira',
    monetary_symbol: '₺',
    flag_code: 'tr',
  },
  TTD: {
    unit_value: 0,
    country_name: 'Trinidad and Tobago',
    currency_code: 'TTD',
    currency_name: 'Trinidad and Tobago Dollar',
    monetary_symbol: '$',
    flag_code: 'tt',
  },
  TVD: {
    unit_value: 0,
    country_name: 'Tuvalu',
    currency_code: 'TVD',
    currency_name: 'Tuvaluan Dollar',
    monetary_symbol: '$',
    flag_code: 'tv',
  },
  TWD: {
    unit_value: 0,
    country_name: 'Taiwan',
    currency_code: 'TWD',
    currency_name: 'New Taiwan Dollar',
    monetary_symbol: 'NT$',
    flag_code: 'tw',
  },
  TZS: {
    unit_value: 0,
    country_name: 'Tanzania',
    currency_code: 'TZS',
    currency_name: 'Tanzanian Shilling',
    monetary_symbol: 'TSh',
    flag_code: 'tz',
  },
  UAH: {
    unit_value: 0,
    country_name: 'Ukraine',
    currency_code: 'UAH',
    currency_name: 'Ukrainian Hryvnia',
    monetary_symbol: '₴',
    flag_code: 'ua',
  },
  UGX: {
    unit_value: 0,
    country_name: 'Uganda',
    currency_code: 'UGX',
    currency_name: 'Ugandan Shilling',
    monetary_symbol: 'USh',
    flag_code: 'ug',
  },
  USD: {
    unit_value: 0,
    country_name: 'United States of America',
    currency_code: 'USD',
    currency_name: 'United States Dollar',
    monetary_symbol: '$',
    flag_code: 'us',
  },
  UYU: {
    unit_value: 0,
    country_name: 'Uruguay',
    currency_code: 'UYU',
    currency_name: 'Uruguayan Peso',
    monetary_symbol: '$',
    flag_code: 'uy',
  },
  UZS: {
    unit_value: 0,
    country_name: 'Uzbekistan',
    currency_code: 'UZS',
    currency_name: 'Uzbekistani Som',
    monetary_symbol: 'UZS',
    flag_code: 'uz',
  },
  VES: {
    unit_value: 0,
    country_name: 'Venezuela',
    currency_code: 'VES',
    currency_name: 'Venezuelan Bolívar',
    monetary_symbol: 'Bs.S.',
    flag_code: 've',
  },
  VND: {
    unit_value: 0,
    country_name: 'Vietnam',
    currency_code: 'VND',
    currency_name: 'Vietnamese Dong',
    monetary_symbol: '₫',
    flag_code: 'vn',
  },
  VUV: {
    unit_value: 0,
    country_name: 'Vanuatu',
    currency_code: 'VUV',
    currency_name: 'Vanuatu Vatu',
    monetary_symbol: 'Vt',
    flag_code: 'vu',
  },
  WST: {
    unit_value: 0,
    country_name: 'Samoa',
    currency_code: 'WST',
    currency_name: 'Samoan Tala',
    monetary_symbol: 'T',
    flag_code: 'ws',
  },
  XAF: {
    unit_value: 0,
    country_name: 'Central African Republic',
    currency_code: 'XAF',
    currency_name: 'Central African CFA Franc',
    monetary_symbol: 'FCFA',
    flag_code: 'cf',
  },
  XCD: {
    unit_value: 0,
    country_name: 'Organisation of Eastern Caribbean States',
    currency_code: 'XCD',
    currency_name: 'Eastern Caribbean Dollar',
    monetary_symbol: '$',
    flag_code: 'dm',
  },
  XDR: {
    unit_value: 0,
    country_name: 'International Monetary Fund',
    currency_code: 'XDR',
    currency_name: 'Special Drawing Rights',
    monetary_symbol: 'XDR',
    flag_code: 'un',
  },
  XOF: {
    unit_value: 0,
    country_name: 'West African Economic and Monetary Union',
    currency_code: 'XOF',
    currency_name: 'West African CFA Franc',
    monetary_symbol: 'CFA',
    flag_code: 'sn',
  },
  XPF: {
    unit_value: 0,
    country_name: 'French Territories',
    currency_code: 'XPF',
    currency_name: 'CFP Franc',
    monetary_symbol: '₣',
    flag_code: 'tf',
  },
  YER: {
    unit_value: 0,
    country_name: 'Yemen',
    currency_code: 'YER',
    currency_name: 'Yemeni Rial',
    monetary_symbol: '﷼',
    flag_code: 'ye',
  },
  ZAR: {
    unit_value: 0,
    country_name: 'South Africa',
    currency_code: 'ZAR',
    currency_name: 'South African Rand',
    monetary_symbol: 'R',
    flag_code: 'za',
  },
  ZMW: {
    unit_value: 0,
    country_name: 'Zambia',
    currency_code: 'ZMW',
    currency_name: 'Zambian Kwacha',
    monetary_symbol: 'ZK',
    flag_code: 'zm',
  },
  ZWL: {
    unit_value: 0,
    country_name: 'Zimbabwe',
    currency_code: 'ZWL',
    currency_name: 'Zimbabwean Dollar',
    monetary_symbol: '$',
    flag_code: 'zw',
  },
};
