import { Currencies } from '../../@types/currencies';

export const PtBrCountries: Currencies = {
  EUR: {
    unit_value: 0,
    country_name: 'União Europeia',
    currency_code: 'EUR',
    currency_name: 'Euro',
    monetary_symbol: '€',
  },
  AED: {
    unit_value: 0,
    country_name: 'Emirados Árabes Unidos',
    currency_code: 'AED',
    currency_name: 'Dirham dos Emirados Árabes Unidos',
    monetary_symbol: 'د.إ',
  },
  AFN: {
    unit_value: 0,
    country_name: 'Afeganistão',
    currency_code: 'AFN',
    currency_name: 'Afegani Afegão',
    monetary_symbol: '؋',
  },
  ALL: {
    unit_value: 0,
    country_name: 'Albânia',
    currency_code: 'ALL',
    currency_name: 'Lek Albanês',
    monetary_symbol: 'L',
  },
  AMD: {
    unit_value: 0,
    country_name: 'Armênia',
    currency_code: 'AMD',
    currency_name: 'Dram Armênio',
    monetary_symbol: '֏',
  },
  ANG: {
    unit_value: 0,
    country_name: 'Antilhas Neerlandesas',
    currency_code: 'ANG',
    currency_name: 'Florim das Antilhas Neerlandesas',
    monetary_symbol: 'ƒ',
  },
  AOA: {
    unit_value: 0,
    country_name: 'Angola',
    currency_code: 'AOA',
    currency_name: 'Kwanza Angolano',
    monetary_symbol: 'Kz',
  },
  ARS: {
    unit_value: 0,
    country_name: 'Argentina',
    currency_code: 'ARS',
    currency_name: 'Peso Argentino',
    monetary_symbol: '$',
  },
  AUD: {
    unit_value: 0,
    country_name: 'Austrália',
    currency_code: 'AUD',
    currency_name: 'Dólar Australiano',
    monetary_symbol: '$',
  },
  AWG: {
    unit_value: 0,
    country_name: 'Aruba',
    currency_code: 'AWG',
    currency_name: 'Florim de Aruba',
    monetary_symbol: 'Afl',
  },
  AZN: {
    unit_value: 0,
    country_name: 'Azerbaijão',
    currency_code: 'AZN',
    currency_name: 'Manat Azerbaijano',
    monetary_symbol: '₼',
  },
  BAM: {
    unit_value: 0,
    country_name: 'Bósnia e Herzegovina',
    currency_code: 'BAM',
    currency_name: 'Marco Conversível da Bósnia e Herzegovina',
    monetary_symbol: 'KM',
  },
  BBD: {
    unit_value: 0,
    country_name: 'Barbados',
    currency_code: 'BBD',
    currency_name: 'Dólar de Barbados',
    monetary_symbol: 'Bds$',
  },
  BDT: {
    unit_value: 0,
    country_name: 'Bangladesh',
    currency_code: 'BDT',
    currency_name: 'Taka de Bangladesh',
    monetary_symbol: '৳',
  },
  BGN: {
    unit_value: 0,
    country_name: 'Bulgária',
    currency_code: 'BGN',
    currency_name: 'Lev Búlgaro',
    monetary_symbol: 'лв',
  },
  BHD: {
    unit_value: 0,
    country_name: 'Bahrein',
    currency_code: 'BHD',
    currency_name: 'Dinar Bahreiniano',
    monetary_symbol: 'BD',
  },
  BIF: {
    unit_value: 0,
    country_name: 'Burundi',
    currency_code: 'BIF',
    currency_name: 'Franco de Burundi',
    monetary_symbol: 'FBu',
  },
  BMD: {
    unit_value: 0,
    country_name: 'Bermudas',
    currency_code: 'BMD',
    currency_name: 'Dólar das Bermudas',
    monetary_symbol: 'BD$',
  },
  BND: {
    unit_value: 0,
    country_name: 'Brunei',
    currency_code: 'BND',
    currency_name: 'Dólar de Brunei',
    monetary_symbol: 'B$',
  },
  BOB: {
    unit_value: 0,
    country_name: 'Bolívia',
    currency_code: 'BOB',
    currency_name: 'Boliviano Boliviano',
    monetary_symbol: 'Bs.',
  },
  BRL: {
    unit_value: 0,
    country_name: 'Brasil',
    currency_code: 'BRL',
    currency_name: 'Real Brasileiro',
    monetary_symbol: 'R$',
  },
  BSD: {
    unit_value: 0,
    country_name: 'Bahamas',
    currency_code: 'BSD',
    currency_name: 'Dólar das Bahamas',
    monetary_symbol: 'BSD$',
  },
  BTN: {
    unit_value: 0,
    country_name: 'Butão',
    currency_code: 'BTN',
    currency_name: 'Ngultrum Butanês',
    monetary_symbol: 'Nu.',
  },
  BWP: {
    unit_value: 0,
    country_name: 'Botsuana',
    currency_code: 'BWP',
    currency_name: 'Pula Botsuanesa',
    monetary_symbol: 'P',
  },
  BYN: {
    unit_value: 0,
    country_name: 'Bielorrússia',
    currency_code: 'BYN',
    currency_name: 'Rublo Bielorrusso',
    monetary_symbol: 'Br',
  },
  BZD: {
    unit_value: 0,
    country_name: 'Belize',
    currency_code: 'BZD',
    currency_name: 'Dólar do Belize',
    monetary_symbol: 'BZ$',
  },
  CAD: {
    unit_value: 0,
    country_name: 'Canadá',
    currency_code: 'CAD',
    currency_name: 'Dólar Canadense',
    monetary_symbol: 'CA$',
  },
  CDF: {
    unit_value: 0,
    country_name: 'República Democrática do Congo',
    currency_code: 'CDF',
    currency_name: 'Franco Congolês',
    monetary_symbol: 'FC',
  },
  CHF: {
    unit_value: 0,
    country_name: 'Suíça',
    currency_code: 'CHF',
    currency_name: 'Franco Suíço',
    monetary_symbol: 'CHF',
  },
  CLP: {
    unit_value: 0,
    country_name: 'Chile',
    currency_code: 'CLP',
    currency_name: 'Peso Chileno',
    monetary_symbol: 'CLP$',
  },
  CNY: {
    unit_value: 0,
    country_name: 'China',
    currency_code: 'CNY',
    currency_name: 'Renminbi Chinês',
    monetary_symbol: '¥',
  },
  COP: {
    unit_value: 0,
    country_name: 'Colômbia',
    currency_code: 'COP',
    currency_name: 'Peso Colombiano',
    monetary_symbol: 'COL$',
  },
  CRC: {
    unit_value: 0,
    country_name: 'Costa Rica',
    currency_code: 'CRC',
    currency_name: 'Colón da Costa Rica',
    monetary_symbol: '₡',
  },
  CUP: {
    unit_value: 0,
    country_name: 'Cuba',
    currency_code: 'CUP',
    currency_name: 'Peso Cubano',
    monetary_symbol: 'CUP$',
  },
  CVE: {
    unit_value: 0,
    country_name: 'Cabo Verde',
    currency_code: 'CVE',
    currency_name: 'Escudo Cabo-Verdiano',
    monetary_symbol: 'Esc',
  },
  CZK: {
    unit_value: 0,
    country_name: 'República Tcheca',
    currency_code: 'CZK',
    currency_name: 'Coroa Tcheca',
    monetary_symbol: 'Kč',
  },
  DJF: {
    unit_value: 0,
    country_name: 'Djibuti',
    currency_code: 'DJF',
    currency_name: 'Franco do Djibuti',
    monetary_symbol: 'Fdj',
  },
  DKK: {
    unit_value: 0,
    country_name: 'Dinamarca',
    currency_code: 'DKK',
    currency_name: 'Coroa Dinamarquesa',
    monetary_symbol: 'kr',
  },
  DOP: {
    unit_value: 0,
    country_name: 'República Dominicana',
    currency_code: 'DOP',
    currency_name: 'Peso Dominicano',
    monetary_symbol: 'RD$',
  },
  DZD: {
    unit_value: 0,
    country_name: 'Argélia',
    currency_code: 'DZD',
    currency_name: 'Dinar Argelino',
    monetary_symbol: 'د.ج',
  },
  EGP: {
    unit_value: 0,
    country_name: 'Egito',
    currency_code: 'EGP',
    currency_name: 'Libra Egípcia',
    monetary_symbol: 'E£',
  },
  ERN: {
    unit_value: 0,
    country_name: 'Eritreia',
    currency_code: 'ERN',
    currency_name: 'Nakfa Eritreia',
    monetary_symbol: 'Nfk',
  },
  ETB: {
    unit_value: 0,
    country_name: 'Etiópia',
    currency_code: 'ETB',
    currency_name: 'Birr Etíope',
    monetary_symbol: 'Br',
  },
  FJD: {
    unit_value: 0,
    country_name: 'Fiji',
    currency_code: 'FJD',
    currency_name: 'Dólar Fijiano',
    monetary_symbol: 'FJ$',
  },
  FKP: {
    unit_value: 0,
    country_name: 'Ilhas Falkland (Malvinas)',
    currency_code: 'FKP',
    currency_name: 'Libra das Ilhas Falkland',
    monetary_symbol: 'FK£',
  },
  FOK: {
    unit_value: 0,
    country_name: 'Ilhas Faroé',
    currency_code: 'FOK',
    currency_name: 'Coroa das Ilhas Faroé',
    monetary_symbol: 'kr',
  },
  GBP: {
    unit_value: 0,
    country_name: 'Reino Unido',
    currency_code: 'GBP',
    currency_name: 'Libra Esterlina',
    monetary_symbol: '£',
  },
  GEL: {
    unit_value: 0,
    country_name: 'Geórgia',
    currency_code: 'GEL',
    currency_name: 'Lari Georgiano',
    monetary_symbol: '₾',
  },
  GGP: {
    unit_value: 0,
    country_name: 'Guernsey',
    currency_code: 'GGP',
    currency_name: 'Libra de Guernsey',
    monetary_symbol: '£',
  },
  GHS: {
    unit_value: 0,
    country_name: 'Gana',
    currency_code: 'GHS',
    currency_name: 'Cedi Ganês',
    monetary_symbol: 'GH₵',
  },
  GIP: {
    unit_value: 0,
    country_name: 'Gibraltar',
    currency_code: 'GIP',
    currency_name: 'Libra de Gibraltar',
    monetary_symbol: '£',
  },
  GMD: {
    unit_value: 0,
    country_name: 'Gâmbia',
    currency_code: 'GMD',
    currency_name: 'Dalasi Gambiano',
    monetary_symbol: 'D',
  },
  GNF: {
    unit_value: 0,
    country_name: 'Guiné',
    currency_code: 'GNF',
    currency_name: 'Franco Guineense',
    monetary_symbol: 'FG',
  },
  GTQ: {
    unit_value: 0,
    country_name: 'Guatemala',
    currency_code: 'GTQ',
    currency_name: 'Quetzal Guatemalteco',
    monetary_symbol: 'Q',
  },
  GYD: {
    unit_value: 0,
    country_name: 'Guiana',
    currency_code: 'GYD',
    currency_name: 'Dólar Guianense',
    monetary_symbol: 'GY$',
  },
  HKD: {
    unit_value: 0,
    country_name: 'Hong Kong',
    currency_code: 'HKD',
    currency_name: 'Dólar de Hong Kong',
    monetary_symbol: 'HK$',
  },
  HNL: {
    unit_value: 0,
    country_name: 'Honduras',
    currency_code: 'HNL',
    currency_name: 'Lempira Hondurenha',
    monetary_symbol: 'L',
  },
  HRK: {
    unit_value: 0,
    country_name: 'Croácia',
    currency_code: 'HRK',
    currency_name: 'Kuna Croata',
    monetary_symbol: 'kn',
  },
  HTG: {
    unit_value: 0,
    country_name: 'Haiti',
    currency_code: 'HTG',
    currency_name: 'Gourde Haitiano',
    monetary_symbol: 'G',
  },
  HUF: {
    unit_value: 0,
    country_name: 'Hungria',
    currency_code: 'HUF',
    currency_name: 'Forint Húngaro',
    monetary_symbol: 'Ft',
  },
  IDR: {
    unit_value: 0,
    country_name: 'Indonésia',
    currency_code: 'IDR',
    currency_name: 'Rupia Indonésia',
    monetary_symbol: 'Rp',
  },
  ILS: {
    unit_value: 0,
    country_name: 'Israel',
    currency_code: 'ILS',
    currency_name: 'Novo Shekel Israelense',
    monetary_symbol: '₪',
  },
  IMP: {
    unit_value: 0,
    country_name: 'Ilha de Man',
    currency_code: 'IMP',
    currency_name: 'Libra da Ilha de Man',
    monetary_symbol: '£',
  },
  INR: {
    unit_value: 0,
    country_name: 'Índia',
    currency_code: 'INR',
    currency_name: 'Rupia Indiana',
    monetary_symbol: '₹',
  },
  IQD: {
    unit_value: 0,
    country_name: 'Iraque',
    currency_code: 'IQD',
    currency_name: 'Dinar Iraquiano',
    monetary_symbol: 'ع.د',
  },
  IRR: {
    unit_value: 0,
    country_name: 'Irã',
    currency_code: 'IRR',
    currency_name: 'Rial Iraniano',
    monetary_symbol: '﷼',
  },
  ISK: {
    unit_value: 0,
    country_name: 'Islândia',
    currency_code: 'ISK',
    currency_name: 'Coroa Islandesa',
    monetary_symbol: 'kr',
  },
  JEP: {
    unit_value: 0,
    country_name: 'Jersey',
    currency_code: 'JEP',
    currency_name: 'Libra de Jersey',
    monetary_symbol: '£',
  },
  JMD: {
    unit_value: 0,
    country_name: 'Jamaica',
    currency_code: 'JMD',
    currency_name: 'Dólar Jamaicano',
    monetary_symbol: 'J$',
  },
  JOD: {
    unit_value: 0,
    country_name: 'Jordânia',
    currency_code: 'JOD',
    currency_name: 'Dinar Jordaniano',
    monetary_symbol: 'د.ا',
  },
  JPY: {
    unit_value: 0,
    country_name: 'Japão',
    currency_code: 'JPY',
    currency_name: 'Iene Japonês',
    monetary_symbol: '¥',
  },
  KES: {
    unit_value: 0,
    country_name: 'Quênia',
    currency_code: 'KES',
    currency_name: 'Xelim Queniano',
    monetary_symbol: 'Ksh',
  },
  KGS: {
    unit_value: 0,
    country_name: 'Quirguistão',
    currency_code: 'KGS',
    currency_name: 'Som Quirguistanês',
    monetary_symbol: 'с',
  },
  KHR: {
    unit_value: 0,
    country_name: 'Camboja',
    currency_code: 'KHR',
    currency_name: 'Riel Cambojano',
    monetary_symbol: '៛',
  },
  KID: {
    unit_value: 0,
    country_name: 'Kiribati',
    currency_code: 'KID',
    currency_name: 'Dólar de Kiribati',
    monetary_symbol: '$',
  },
  KMF: {
    unit_value: 0,
    country_name: 'Comores',
    currency_code: 'KMF',
    currency_name: 'Franco Comorense',
    monetary_symbol: 'CF',
  },
  KRW: {
    unit_value: 0,
    country_name: 'Coreia do Sul',
    currency_code: 'KRW',
    currency_name: 'Won Sul-Coreano',
    monetary_symbol: '₩',
  },
  KWD: {
    unit_value: 0,
    country_name: 'Kuwait',
    currency_code: 'KWD',
    currency_name: 'Dinar Kuwaitiano',
    monetary_symbol: 'د.ك',
  },
  KYD: {
    unit_value: 0,
    country_name: 'Ilhas Cayman',
    currency_code: 'KYD',
    currency_name: 'Dólar das Ilhas Cayman',
    monetary_symbol: '$',
  },
  KZT: {
    unit_value: 0,
    country_name: 'Cazaquistão',
    currency_code: 'KZT',
    currency_name: 'Tenge Cazaque',
    monetary_symbol: '₸',
  },
  LAK: {
    unit_value: 0,
    country_name: 'Laos',
    currency_code: 'LAK',
    currency_name: 'Kip de Laos',
    monetary_symbol: '₭',
  },
  LBP: {
    unit_value: 0,
    country_name: 'Líbano',
    currency_code: 'LBP',
    currency_name: 'Libra Libanesa',
    monetary_symbol: 'ل.ل',
  },
  LKR: {
    unit_value: 0,
    country_name: 'Sri Lanka',
    currency_code: 'LKR',
    currency_name: 'Rupia do Sri Lanka',
    monetary_symbol: 'රු',
  },
  LRD: {
    unit_value: 0,
    country_name: 'Libéria',
    currency_code: 'LRD',
    currency_name: 'Dólar Liberiano',
    monetary_symbol: '$',
  },
  LSL: {
    unit_value: 0,
    country_name: 'Lesoto',
    currency_code: 'LSL',
    currency_name: 'Loti do Lesoto',
    monetary_symbol: 'L',
  },
  LYD: {
    unit_value: 0,
    country_name: 'Líbia',
    currency_code: 'LYD',
    currency_name: 'Dinar Líbio',
    monetary_symbol: 'ل.د',
  },
  MAD: {
    unit_value: 0,
    country_name: 'Marrocos',
    currency_code: 'MAD',
    currency_name: 'Dirham Marroquino',
    monetary_symbol: 'د.م.',
  },
  MDL: {
    unit_value: 0,
    country_name: 'Moldávia',
    currency_code: 'MDL',
    currency_name: 'Leu Moldavo',
    monetary_symbol: 'L',
  },
  MGA: {
    unit_value: 0,
    country_name: 'Madagáscar',
    currency_code: 'MGA',
    currency_name: 'Ariary de Madagáscar',
    monetary_symbol: 'Ar',
  },
  MKD: {
    unit_value: 0,
    country_name: 'Macedônia do Norte',
    currency_code: 'MKD',
    currency_name: 'Dinar Macedônio',
    monetary_symbol: 'ден',
  },
  MMK: {
    unit_value: 0,
    country_name: 'Mianmar',
    currency_code: 'MMK',
    currency_name: 'Kyat de Mianmar',
    monetary_symbol: 'Ks',
  },
  MNT: {
    unit_value: 0,
    country_name: 'Mongólia',
    currency_code: 'MNT',
    currency_name: 'Tugrik Mongol',
    monetary_symbol: '₮',
  },
  MOP: {
    unit_value: 0,
    country_name: 'Macau',
    currency_code: 'MOP',
    currency_name: 'Pataca de Macau',
    monetary_symbol: 'P',
  },
  MRU: {
    unit_value: 0,
    country_name: 'Mauritânia',
    currency_code: 'MRU',
    currency_name: 'Ouguiya da Mauritânia',
    monetary_symbol: 'UM',
  },
  MUR: {
    unit_value: 0,
    country_name: 'Maurícia',
    currency_code: 'MUR',
    currency_name: 'Rupia da Maurícia',
    monetary_symbol: '₨',
  },
  MVR: {
    unit_value: 0,
    country_name: 'Maldivas',
    currency_code: 'MVR',
    currency_name: 'Rufiyaa das Maldivas',
    monetary_symbol: 'ރ.',
  },
  MWK: {
    unit_value: 0,
    country_name: 'Malawi',
    currency_code: 'MWK',
    currency_name: 'Kwacha do Malawi',
    monetary_symbol: 'MK',
  },
  MXN: {
    unit_value: 0,
    country_name: 'México',
    currency_code: 'MXN',
    currency_name: 'Peso Mexicano',
    monetary_symbol: '$',
  },
  MYR: {
    unit_value: 0,
    country_name: 'Malásia',
    currency_code: 'MYR',
    currency_name: 'Ringgit da Malásia',
    monetary_symbol: 'RM',
  },
  MZN: {
    unit_value: 0,
    country_name: 'Moçambique',
    currency_code: 'MZN',
    currency_name: 'Metical Moçambicano',
    monetary_symbol: 'MT',
  },
  NAD: {
    unit_value: 0,
    country_name: 'Namíbia',
    currency_code: 'NAD',
    currency_name: 'Dólar da Namíbia',
    monetary_symbol: '$',
  },
  NGN: {
    unit_value: 0,
    country_name: 'Nigéria',
    currency_code: 'NGN',
    currency_name: 'Naira Nigeriana',
    monetary_symbol: '₦',
  },
  NIO: {
    unit_value: 0,
    country_name: 'Nicarágua',
    currency_code: 'NIO',
    currency_name: 'Córdoba Nicaraguense',
    monetary_symbol: 'C$',
  },
  NOK: {
    unit_value: 0,
    country_name: 'Noruega',
    currency_code: 'NOK',
    currency_name: 'Coroa Norueguesa',
    monetary_symbol: 'kr',
  },
  NPR: {
    unit_value: 0,
    country_name: 'Nepal',
    currency_code: 'NPR',
    currency_name: 'Rupia Nepalesa',
    monetary_symbol: 'रू',
  },
  NZD: {
    unit_value: 0,
    country_name: 'Nova Zelândia',
    currency_code: 'NZD',
    currency_name: 'Dólar da Nova Zelândia',
    monetary_symbol: '$',
  },
  OMR: {
    unit_value: 0,
    country_name: 'Omã',
    currency_code: 'OMR',
    currency_name: 'Rial de Omã',
    monetary_symbol: 'ر.ع.',
  },
  PAB: {
    unit_value: 0,
    country_name: 'Panamá',
    currency_code: 'PAB',
    currency_name: 'Balboa Panamenho',
    monetary_symbol: 'B/.',
  },
  PEN: {
    unit_value: 0,
    country_name: 'Peru',
    currency_code: 'PEN',
    currency_name: 'Sol Peruano',
    monetary_symbol: 'S/.',
  },
  PGK: {
    unit_value: 0,
    country_name: 'Papua-Nova Guiné',
    currency_code: 'PGK',
    currency_name: 'Kina de Papua-Nova Guiné',
    monetary_symbol: 'K',
  },
  PHP: {
    unit_value: 0,
    country_name: 'Filipinas',
    currency_code: 'PHP',
    currency_name: 'Peso Filipino',
    monetary_symbol: '₱',
  },
  PKR: {
    unit_value: 0,
    country_name: 'Paquistão',
    currency_code: 'PKR',
    currency_name: 'Rúpia Paquistanesa',
    monetary_symbol: '₨',
  },
  PLN: {
    unit_value: 0,
    country_name: 'Polônia',
    currency_code: 'PLN',
    currency_name: 'Złoty Polonês',
    monetary_symbol: 'zł',
  },
  PYG: {
    unit_value: 0,
    country_name: 'Paraguai',
    currency_code: 'PYG',
    currency_name: 'Guarani Paraguaio',
    monetary_symbol: '₲',
  },
  QAR: {
    unit_value: 0,
    country_name: 'Catar',
    currency_code: 'QAR',
    currency_name: 'Rial do Catar',
    monetary_symbol: 'ر.ق.',
  },
  RON: {
    unit_value: 0,
    country_name: 'Romênia',
    currency_code: 'RON',
    currency_name: 'Leu Romeno',
    monetary_symbol: 'lei',
  },
  RSD: {
    unit_value: 0,
    country_name: 'Sérvia',
    currency_code: 'RSD',
    currency_name: 'Dinar Sérvio',
    monetary_symbol: 'дин.',
  },
  RUB: {
    unit_value: 0,
    country_name: 'Rússia',
    currency_code: 'RUB',
    currency_name: 'Rublo Russo',
    monetary_symbol: '₽',
  },
  RWF: {
    unit_value: 0,
    country_name: 'Ruanda',
    currency_code: 'RWF',
    currency_name: 'Franco Ruandês',
    monetary_symbol: 'FRw',
  },
  SAR: {
    unit_value: 0,
    country_name: 'Arábia Saudita',
    currency_code: 'SAR',
    currency_name: 'Rial Saudita',
    monetary_symbol: 'ر.س.',
  },
  SBD: {
    unit_value: 0,
    country_name: 'Ilhas Salomão',
    currency_code: 'SBD',
    currency_name: 'Dólar das Ilhas Salomão',
    monetary_symbol: '$',
  },
  SCR: {
    unit_value: 0,
    country_name: 'Seychelles',
    currency_code: 'SCR',
    currency_name: 'Rupia de Seychelles',
    monetary_symbol: '₨',
  },
  SDG: {
    unit_value: 0,
    country_name: 'Sudão',
    currency_code: 'SDG',
    currency_name: 'Libra Sudanesa',
    monetary_symbol: '£',
  },
  SEK: {
    unit_value: 0,
    country_name: 'Suécia',
    currency_code: 'SEK',
    currency_name: 'Coroa Sueca',
    monetary_symbol: 'kr',
  },
  SGD: {
    unit_value: 0,
    country_name: 'Singapura',
    currency_code: 'SGD',
    currency_name: 'Dólar de Singapura',
    monetary_symbol: '$',
  },
  SHP: {
    unit_value: 0,
    country_name: 'Santa Helena',
    currency_code: 'SHP',
    currency_name: 'Libra de Santa Helena',
    monetary_symbol: '£',
  },
  SLE: {
    unit_value: 0,
    country_name: 'Serra Leoa',
    currency_code: 'SLE',
    currency_name: 'Leone de Serra Leoa',
    monetary_symbol: 'Le',
  },
  SLL: {
    unit_value: 0,
    country_name: 'Serra Leoa',
    currency_code: 'SLL',
    currency_name: 'Leone de Serra Leoa',
    monetary_symbol: 'Le',
  },
  SOS: {
    unit_value: 0,
    country_name: 'Somália',
    currency_code: 'SOS',
    currency_name: 'Xelim Somali',
    monetary_symbol: 'Sh',
  },
  SRD: {
    unit_value: 0,
    country_name: 'Suriname',
    currency_code: 'SRD',
    currency_name: 'Dólar Surinamês',
    monetary_symbol: '$',
  },
  SSP: {
    unit_value: 0,
    country_name: 'Sudão do Sul',
    currency_code: 'SSP',
    currency_name: 'Libra Sul-Sudanesa',
    monetary_symbol: '£',
  },
  STN: {
    unit_value: 0,
    country_name: 'São Tomé e Príncipe',
    currency_code: 'STN',
    currency_name: 'Dobra de São Tomé e Príncipe',
    monetary_symbol: 'Db',
  },
  SYP: {
    unit_value: 0,
    country_name: 'Síria',
    currency_code: 'SYP',
    currency_name: 'Libra Síria',
    monetary_symbol: 'ل.س',
  },
  SZL: {
    unit_value: 0,
    country_name: 'Suazilândia',
    currency_code: 'SZL',
    currency_name: 'Lilangeni da Suazilândia',
    monetary_symbol: 'E',
  },
  THB: {
    unit_value: 0,
    country_name: 'Tailândia',
    currency_code: 'THB',
    currency_name: 'Baht Tailandês',
    monetary_symbol: '฿',
  },
  TJS: {
    unit_value: 0,
    country_name: 'Tajiquistão',
    currency_code: 'TJS',
    currency_name: 'Somoni do Tajiquistão',
    monetary_symbol: 'ЅМ',
  },
  TMT: {
    unit_value: 0,
    country_name: 'Turcomenistão',
    currency_code: 'TMT',
    currency_name: 'Manat do Turcomenistão',
    monetary_symbol: 'T',
  },
  TND: {
    unit_value: 0,
    country_name: 'Tunísia',
    currency_code: 'TND',
    currency_name: 'Dinar Tunisiano',
    monetary_symbol: 'د.ت',
  },
  TOP: {
    unit_value: 0,
    country_name: 'Tonga',
    currency_code: 'TOP',
    currency_name: 'Paʻanga de Tonga',
    monetary_symbol: 'T$',
  },
  TRY: {
    unit_value: 0,
    country_name: 'Turquia',
    currency_code: 'TRY',
    currency_name: 'Lira Turca',
    monetary_symbol: '₺',
  },
  TTD: {
    unit_value: 0,
    country_name: 'Trinidad e Tobago',
    currency_code: 'TTD',
    currency_name: 'Dólar de Trinidad e Tobago',
    monetary_symbol: '$',
  },
  TVD: {
    unit_value: 0,
    country_name: 'Tuvalu',
    currency_code: 'TVD',
    currency_name: 'Dólar de Tuvalu',
    monetary_symbol: '$',
  },
  TWD: {
    unit_value: 0,
    country_name: 'Taiwan',
    currency_code: 'TWD',
    currency_name: 'Novo Dólar de Taiwan',
    monetary_symbol: 'NT$',
  },
  TZS: {
    unit_value: 0,
    country_name: 'Tanzânia',
    currency_code: 'TZS',
    currency_name: 'Xelim da Tanzânia',
    monetary_symbol: 'TSh',
  },
  UAH: {
    unit_value: 0,
    country_name: 'Ucrânia',
    currency_code: 'UAH',
    currency_name: 'Hryvnia Ucraniano',
    monetary_symbol: '₴',
  },
  UGX: {
    unit_value: 0,
    country_name: 'Uganda',
    currency_code: 'UGX',
    currency_name: 'Xelim de Uganda',
    monetary_symbol: 'USh',
  },
  USD: {
    unit_value: 0,
    country_name: 'Estados Unidos',
    currency_code: 'USD',
    currency_name: 'Dólar Americano',
    monetary_symbol: '$',
  },
  UYU: {
    unit_value: 0,
    country_name: 'Uruguai',
    currency_code: 'UYU',
    currency_name: 'Peso Uruguaio',
    monetary_symbol: '$',
  },
  UZS: {
    unit_value: 0,
    country_name: 'Uzbequistão',
    currency_code: 'UZS',
    currency_name: 'Som Uzbeque',
    monetary_symbol: 'UZS',
  },
  VES: {
    unit_value: 0,
    country_name: 'Venezuela',
    currency_code: 'VES',
    currency_name: 'Bolívar Venezuelano',
    monetary_symbol: 'Bs.S.',
  },
  VND: {
    unit_value: 0,
    country_name: 'Vietnã',
    currency_code: 'VND',
    currency_name: 'Dong Vietnamita',
    monetary_symbol: '₫',
  },
  VUV: {
    unit_value: 0,
    country_name: 'Vanuatu',
    currency_code: 'VUV',
    currency_name: 'Vatu de Vanuatu',
    monetary_symbol: 'Vt',
  },
  WST: {
    unit_value: 0,
    country_name: 'Samoa',
    currency_code: 'WST',
    currency_name: 'Tala Samoano',
    monetary_symbol: 'T',
  },
  XAF: {
    unit_value: 0,
    country_name: 'África Central',
    currency_code: 'XAF',
    currency_name: 'Franco CFA da África Central',
    monetary_symbol: 'FCFA',
  },
  XCD: {
    unit_value: 0,
    country_name: 'Organização dos Estados do Caribe Oriental',
    currency_code: 'XCD',
    currency_name: 'Dólar do Caribe Oriental',
    monetary_symbol: '$',
  },
  XDR: {
    unit_value: 0,
    country_name: 'Fundo Monetário Internacional',
    currency_code: 'XDR',
    currency_name: 'Direitos Especiais de Giro',
    monetary_symbol: 'XDR',
  },
  XOF: {
    unit_value: 0,
    country_name: 'União Econômica e Monetária da África Ocidental',
    currency_code: 'XOF',
    currency_name: 'Franco CFA da África Ocidental',
    monetary_symbol: 'CFA',
  },
  XPF: {
    unit_value: 0,
    country_name: 'Territórios Ultramarinos da França',
    currency_code: 'XPF',
    currency_name: 'Franco CFP',
    monetary_symbol: '₣',
  },
  YER: {
    unit_value: 0,
    country_name: 'Iémen',
    currency_code: 'YER',
    currency_name: 'Rial Iemenita',
    monetary_symbol: '﷼',
  },
  ZAR: {
    unit_value: 0,
    country_name: 'África do Sul',
    currency_code: 'ZAR',
    currency_name: 'Rand Sul-Africano',
    monetary_symbol: 'R',
  },
  ZMW: {
    unit_value: 0,
    country_name: 'Zâmbia',
    currency_code: 'ZMW',
    currency_name: 'Kwacha Zambiano',
    monetary_symbol: 'ZK',
  },
  ZWL: {
    unit_value: 0,
    country_name: 'Zimbábue',
    currency_code: 'ZWL',
    currency_name: 'Dólar do Zimbábue',
    monetary_symbol: '$',
  },
};
